# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

provider "aws" {
  region = "eu-central-1"
  profile = "homepage-production"
  assume_role {
    role_arn  = "arn:aws:iam::098961484923:role/OrganizationAccountAccessRole"
  }
  version = "~> 3.0"
}

provider "aws" {
  region = "eu-central-1"
  alias = "homepage-shared-services"
  profile = "homepage-shared-services"
  assume_role {
    role_arn  = "arn:aws:iam::391559760545:role/OrganizationAccountAccessRole"
  }
  version = "~> 3.0"
}

provider "aws" {
  alias = "homepage-master"
  region = "eu-central-1"
  profile = "homepage-master"
  version = "~> 3.0"
}
