# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    region         = "eu-central-1"
    bucket         = "snowplow-ecs-terraform-terragrunt-state"
    dynamodb_table = "snowplow-ecs-terraform-terragrunt-state-production"
    encrypt        = true
    key            = "admin/terraform-terragrunt-production.tfstate"
  }
}
